/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/blogs/': RouteRecordInfo<'/blogs/', '/blogs', Record<never, never>, Record<never, never>>,
    '/blogs/[id]/': RouteRecordInfo<'/blogs/[id]/', '/blogs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/blogs/[id]/posts/[postId]': RouteRecordInfo<'/blogs/[id]/posts/[postId]', '/blogs/:id/posts/:postId', { id: ParamValue<true>, postId: ParamValue<true> }, { id: ParamValue<false>, postId: ParamValue<false> }>,
    '/error/401': RouteRecordInfo<'/error/401', '/error/401', Record<never, never>, Record<never, never>>,
    '/error/403': RouteRecordInfo<'/error/403', '/error/403', Record<never, never>, Record<never, never>>,
    '/error/404': RouteRecordInfo<'/error/404', '/error/404', Record<never, never>, Record<never, never>>,
    '/gallery': RouteRecordInfo<'/gallery', '/gallery', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/messages': RouteRecordInfo<'/messages', '/messages', Record<never, never>, Record<never, never>>,
    '/notifications': RouteRecordInfo<'/notifications', '/notifications', Record<never, never>, Record<never, never>>,
    '/photo/[id]': RouteRecordInfo<'/photo/[id]', '/photo/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/profiles/': RouteRecordInfo<'/profiles/', '/profiles', Record<never, never>, Record<never, never>>,
    '/profiles/[id]': RouteRecordInfo<'/profiles/[id]', '/profiles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/store': RouteRecordInfo<'/store', '/store', Record<never, never>, Record<never, never>>,
  }
}
