/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/blogs/': RouteRecordInfo<'/blogs/', '/blogs', Record<never, never>, Record<never, never>>,
    '/blogs/[id]/': RouteRecordInfo<'/blogs/[id]/', '/blogs/:id-:slug', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/blogs/[id]/edit': RouteRecordInfo<'/blogs/[id]/edit', '/blogs/:id-:slug?/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/blogs/[id]/posts/[postId]': RouteRecordInfo<'/blogs/[id]/posts/[postId]', '/blogs/:id-:blogSlug/posts/:postId-:postSlug', { id: ParamValue<true>, postId: ParamValue<true> }, { id: ParamValue<false>, postId: ParamValue<false> }, '/blogs/[id]/posts/[postId]/edit'>,
    '/blogs/[id]/posts/[postId]/edit': RouteRecordInfo<'/blogs/[id]/posts/[postId]/edit', '/blogs/:id-:blogSlug/posts/:postId-:postSlug/edit', { id: ParamValue<true>, postId: ParamValue<true> }, { id: ParamValue<false>, postId: ParamValue<false> }>,
    '/blogs/[id]/posts/': RouteRecordInfo<'/blogs/[id]/posts/', '/blogs/:id-:slug/posts', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/blogs/[id]/posts/new': RouteRecordInfo<'/blogs/[id]/posts/new', '/blogs/:id-:slug/posts/new', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/conversations/': RouteRecordInfo<'/conversations/', '/conversations', Record<never, never>, Record<never, never>>,
    '/conversations/[conversationId]/': RouteRecordInfo<'/conversations/[conversationId]/', '/conversations/:conversationId', { conversationId: ParamValue<true> }, { conversationId: ParamValue<false> }>,
    '/conversations/[conversationId]/[messageId]': RouteRecordInfo<'/conversations/[conversationId]/[messageId]', '/conversations/:conversationId/:messageId', { conversationId: ParamValue<true>, messageId: ParamValue<true> }, { conversationId: ParamValue<false>, messageId: ParamValue<false> }>,
    '/developer/store': RouteRecordInfo<'/developer/store', '/developer/store', Record<never, never>, Record<never, never>>,
    '/error/401': RouteRecordInfo<'/error/401', '/error/401', Record<never, never>, Record<never, never>>,
    '/error/403': RouteRecordInfo<'/error/403', '/error/403', Record<never, never>, Record<never, never>>,
    '/error/404': RouteRecordInfo<'/error/404', '/error/404', Record<never, never>, Record<never, never>>,
    '/error/500': RouteRecordInfo<'/error/500', '/error/500', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/notifications/': RouteRecordInfo<'/notifications/', '/notifications', Record<never, never>, Record<never, never>>,
    '/photos/[id]/': RouteRecordInfo<'/photos/[id]/', '/photos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/photos/[id]/[photoId]': RouteRecordInfo<'/photos/[id]/[photoId]', '/photos/:id/:photoId', { id: ParamValue<true>, photoId: ParamValue<true> }, { id: ParamValue<false>, photoId: ParamValue<false> }>,
    '/profiles/': RouteRecordInfo<'/profiles/', '/profiles', Record<never, never>, Record<never, never>>,
    '/profiles/[id]/': RouteRecordInfo<'/profiles/[id]/', '/profiles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profiles/[id]/edit': RouteRecordInfo<'/profiles/[id]/edit', '/profiles/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/profiles/[id]/notifications': RouteRecordInfo<'/profiles/[id]/notifications', '/profiles/:id/notifications', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
