name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  delete:
    name: Delete head branch
    # Only when merged, from same repo, and not the default branch
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.head.ref != github.event.pull_request.base.repo.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: peter-evans/delete-branch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}

